ElGanadero/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ElGanadero.Model;
using Ganadero.Interfaces.Interfaces;
using Ganadero.Model.Entidades;
using Validators.validatorsEntities;

 using  ElGanadero;


namespace ElGanadero.Controllers
{
    public class VentaController : Controller
    {

        GanaderoEntities4 context = null;
     
        private InterfaceProducto productorepo;
        private ventavalidator validator;
        private InterfaceVenta ventarepo;
        private InterfaceDetalle detallerepo;
         private InterfaceEntidadCliente entidadClirepo;
        
        
        public VentaController(ventavalidator validator, InterfaceProducto productorepo, InterfaceVenta ventarepo, InterfaceEntidadCliente entidadClirepo,InterfaceDetalle detallerepo)
        {
            this.productorepo = productorepo;
            this.ventarepo = ventarepo;
            this.validator = validator;
            this.detallerepo = detallerepo;
            this.entidadClirepo=entidadClirepo;
        }

        public ActionResult Index( int query=1)
        {
           
            
                var dato = ventarepo.ByQueryAll(query);
                return View("Index", dato);
          
          
        }



       [HttpGet]
        public PartialViewResult Detalle(int id)
        {
            context = new GanaderoEntities4();
             var  detalle=context.DetalleVentas.Where(x => x.IdVentas == id).ToList();
            return PartialView(detalle);
        }



        [HttpGet]
        public ViewResult Create(string query="")
        {
            var cliente = entidadClirepo.All();
            ViewData["identiti"] = new SelectList(cliente, "id", "nombre");

            var dato = productorepo.ByQueryAll(query);
            return View("Create",dato);
        }
        [HttpGet]
        public PartialViewResult addproducto(int id, int index)
        {
            var producto = productorepo.Find(id);
            ViewBag.Index = index;
            return PartialView(producto);
        }


        [HttpPost]

        public ActionResult Create(Ganadero.Model.Entidades.Venta venta)
        {

            if (validator.Pass(venta))
            {

               ventarepo.Store(venta);

                TempData["UpdateSuccess"] = "la venta se a guardado correctamente";
                return RedirectToAction("index");
            }

            return View("create", venta);
        }


        [HttpGet]
        public ViewResult anular(int id)
        {
            var data = ventarepo.Find(id);
          
            return View("anular", data);
        }

        [HttpPost]
        public ActionResult anular(Ganadero.Model.Entidades.Venta venta)
        {
            ventarepo.Update(venta);
            TempData["UpdateSuccess"] = "Se Actualizó Correctamente";
            return RedirectToAction("Index");
        }

    }
      

    
}

ElGanadero/Views/Venta/Create.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@model List<Ganadero.Model.Entidades.Producto>
<h2 align="center">REALIZAR VENTA</h2>

@section styles{
    <style>
        .product {
            background-color: rgb(230,244,224);
        }
    </style>
}

@section scripts{
    <script>
        var index = 0;
        $(function aad() {
            $("#productos tbody tr").click(function () {
                $(this).addClass('product').siblings().removeClass('product');
                var id = this.cells[0].textContent;
                $.get('/Venta/addproducto/' + id + '?index=' + index).success(function (respuesta) {
                    $('#productoslis').append(respuesta);
                });
                index++;
            });
        });
    </script>
}


<div class="col-sm-8  col-md-offset-2">

    @if (TempData["UpdateSuccess"] != null)
    {
        <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
    }
    </div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
 <form action="/Venta/Create" method="post">
     <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4>Crear  venta</h4></div>
  <div class="panel-body">
  
  
        <div class="col-md-4" >
         <label for="fecha/">Fecha:</label>
        <input type="date" name="fecha" class="form-control" placeholder="AAAA/MM/DD"></imput>
        </div>

      <div class="col-md-3" >
            <label for="">Tipo Comprobante:</label>
        <select name="tipocomprobante" class="select form-control">
             <option value="Otros">--OTROS--</option>
            <option value="Boleta">Boleta</option>
            <option value="Factura">Factura</option>
        </select>
  </div>

    
     
     <div class="col-md-4">
        <label for="cliente">Cliente: </label>
        <div class="editor-field">
            @Html.DropDownList("identiti")
         @*   @Html.ValidationMessageFor(model => model.IdClasificacion)*@
            
        </div>
    </div>

    

  <form action="/venta/create" method="get">
       <div class="row">
           
        <div>
            <h2>Productos</h2>
        </div>
            <div class="col-md-6">
                <input type="text" align="center" name="query" class="form-control" placeholder="Buscar..." />
            </div>

            <div class="col-md-2">
                <button class="btn btn-primary" align="center">Buscar</button>
            </div>
  </div>
 </form>


    <table id="productos" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre Producto</th>
                <th>Marca</th>
                <th>Precio</th>
                <th>Categoria</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.IdProducto</td>
                    <td>@item.NombreProducto </td>
                    <td>@item.Marca </td>
                    <td>@item.Precio</td>
                    <td>@item.categoria.Descripcion</td>

                    <td>
                        <a href="#" onclick="aad()">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                            Agregar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
    </div>
    <div>
        <h2>Lista Productos</h2>
    </div>

    <table id="listaproductos"   name="detalle" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre Producto</th>
                <th>Marca</th>
                <th>PrecioUni</th>
                <th>Categoria</th>
                <th>cantidad</th>
                <th>precioTo</th>

            </tr>
        </thead>
        <tbody id="productoslis">
        </tbody>
        
    </table>
    <div class="col-md-4">
                <input type="text"  name="total" class="form-control" placeholder="TotalPagar" />
            </div>
   <br />
     <br />
     <br />
    <div >
   
    </div>

      <nav>
  <ul class="pager">
     <button class="btn btn-primary glyphicon glyphicon-floppy-saved">Guardar</button>

              <a href="/venta/index" class="btn btn-danger">
                <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                cancelar
            </a>
  </ul>
</nav>
       </form>
</div>
   </div>
 

ElGanadero/Views/Venta/Detalle.cshtml
@model List<ElGanadero.Model.DetalleVenta>
  
<table class="table">
    <thead>
        <tr>
            <th>Idventa</th>
            <th>producto nombre</th>
            <th>catidad</th>
            <th>precio</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.IdVentas</td>
                <td>@item.Producto.NombreProducto </td>
                <td>@item.cantidad</td>
                 <td>@item.preciodeta</td>
            </tr>
        }
    </tbody>
</table>
     

ElGanadero/Views/Venta/DevolucionOcambio.cshtml
@{
    ViewBag.Title = "DevolucionOcambio";
}

<h2>DevolucionOcambio</h2>

ElGanadero/Views/Venta/addproducto.cshtml
<tr>

   <td><input type="hidden" name="detalleventa[@ViewBag.Index].IdProducto" value="@Model.IdProducto" /></td>
    <td>@Model.NombreProducto</td>
    <td>@Model.Marca</td>
    <td>@Model.Precio</td>
    <td>@Model.categoria.Descripcion</td>
    
    <td><input type="text" name="detalleventa[@ViewBag.Index].Cantidad" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].NombreProducto" value="@Model.NombreProducto" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].preciodeta" value="@Model.Precio*catidad" /></td>
     <td><input type="hidden" name="detalleventa[@ViewBag.Index].IDCategoria" value="@Model.IDCategoria" /></td>
   
</tr>  

ElGanadero/Views/Venta/anular.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@model Ganadero.Model.Entidades.Venta
<h3 align="center>ANULAR VENTA</h3>

<div class="row">
    <div class="col-sm-6  col-md-offset-3">
          <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4>Anulr venta</h4></div>
  <div class="panel-body">
        <form action="/Venta/anular/@Model.ventaID" method="post">
            <div>
                 <h3 align="center>Editar Producto</h3>
            </div>
               </div>

                     <div class="form-group">
                    <label for="Stock/">Anular:</label>
                    <input type="CheckBox" name="estado"  Class="form-control" placeholder="anular"
                       value="@Model.estado" ></imput>
                 </div>
             </div>


           <div class="form-group">
                    <label for="Descripcion/">ventaID:</label>
                    <input type="text" name="ventaID" Class="form-control" 
                        placeholder="descripcion" value="@Model.ventaID"  readonly="true"></input>
                 </div>
            <div class="form-group">
                    <label for="Descripcion/">Id-Cliente:</label>
                    <input type="text" name="identiti" Class="form-control" 
                        placeholder="descripcion" value="@Model.identiti"  readonly="true"></input>
                 </div>
            <div class="form-group">
                    <label for="Descripcion/">tipo comprobante</label>
                    <input type="text" name="tipocomprobante" Class="form-control" 
                        placeholder="descripcion" value="@Model.tipocomprobante" readonly="true"></input>
                         
                 
                 </div>

                    
                     <div class="form-group">
                    <label for="Precio/">fecha:</label>
                    <input type="text" name="fecha"  Class="form-control" 
                        placeholder="fecha" value="@Model.fecha" readonly="true" ></input>
              

                     <div class="form-group">
                    <label for="total"/>Total:</label>
                    <input type="text" name="total"  Class="form-control" placeholder="Marca"
                       value="@Model.total"  readonly="true" readonly="true"></imput>
                 </div>
                                 <div class="form-group">
                    <label for="Stock/">DETALLE ID</label>
                    <input type="text" name="detalleventa"  Class="form-control" placeholder="Marca"
                       value="@Model.detalleventa"  readonly="true"></imput>
                 </div>

                 
            </div>


<nav>
  <ul class="pager">
                 <button class="btn btn-primary glyphicon glyphicon-floppy-saved" >Guardar</button>

             <a href="/Producto/inicio" class="btn btn-danger">

                <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                cancelar
            </a>
  </ul>
</nav>
        </form>
           
    </div>

</div>
</div>

    

ElGanadero/Views/Venta/index.cshtml
<link rel="stylesheet" href="/Content/bootstrap.css">
@model List<Ganadero.Model.Entidades.Venta>

<h2 align="center">lista  de Ventas</h2>

@section styles{
    <style>
        .product {
            background-color: rgb(230,244,224);
        }
    </style>
}

@section scripts{
    <script>
        var index = 0;
        $(function aad() {
            $("#master tbody tr").click(function () {
                $
                $(this).addClass('product').siblings().removeClass('product');
                var id = this.cells[0].textContent;
                $.get('/Venta/Detalle/' + id).success(function (respuesta) {
                    
                    $('#productoslis').append(respuesta);
                });
            });
        });
    </script>
}



<div class="col-sm-12  col-md-offset-0" >

@if (TempData["UpdateSuccess"] != null)
{
    <div class="alert alert-success">@TempData["UpdateSuccess"]</div>
}


   <div class="panel panel-info">
  <div class="panel-heading" style="text-align:center">
      <h4> ventas</h4></div>
  <div class="panel-body">

<form action="/venta/index" method="get">

    <div class="row" >
        <div class="col-md-6">
            <input type="text"name="query" class="form-control" placeholder="Buscar..." />
        </div>
       
        <div class="col-md-2">
            <button class="btn btn-primary"align="center">Buscar</button>
        </div>
         <div class="col-md-2">
            <a href="/venta/Create" class="btn btn-success" style="    margin-bottom: 10px;">Crear</a>
        </div>
    </div>
</form>


<table class="table" id="master">
    <thead>
        <tr>
            <th>Id</th>
            <th>tipo comprobante</th>
            <th>fecha</th>

            <th>id-cliente</th>
            <th>anulada</th>
            <th>total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ventaID</td>
                <td>@item.tipocomprobante </td>
                <td>@item.fecha </td>
                <td>@item.identiti</td>
                <td>@item.estado</td>
                <td>@item.total</td>
               
               <td>
                   <a href="#" onclick="aad( )">
                            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                            Agregar
                        </a>
                   @Ajax.ActionLink("cambio", "Detalle", "Venta", new { id = item.ventaID }, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "detalle" });

               </td>
                <td>
                    <a href="/Venta/anular/@item.ventaID" class="glyphicon glyphicon-pencil">anular</a> |
                  
                </td>
            </tr>
        }
    </tbody>
</table>
     <h3> detalle venta</h3>
         <div id="productoslis">    </div>

     </div>
   </div>
</div>

 
       
    